appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: iZQLSzIbjlTIUBucrZwSRsX7eyebzky8n4E5JTLsU6Dyv1i+OwjVWEoyaGq2/B5jgCZtRyedY2yApWIaDQr1iebJNRId5b1u4A8NgtAmT7p83dsGh0DGIgjvfebnY/FuHczvrZj5EiIf0ONxub+jiTA1Pd7LtuBYwsadF6XoIp2al45nFceo9/QgpzTyGZZpww89d8KukPdFGBoBcosPHp54H31/JSH3gaXmR7P2q6g4P2afkaamhoJ2gjhRxHYfVronz8YwReKcd58hT5hqNMkIO6YiO25igOQCK9KV9JYXinLZSVLVpsApGbt4RNWztxyo1DHhHQVhMo5zt9K0SUgeASJpLbRW8t0wEg4VBIT4KGCdzwSCojv7x4EGODFSxlvT/86Qe5imHqa6Ig1ao5HdMt92RtgZQwoLv1rz3dfiokgDlZgwdNvDN0g6FlUQjU1WFQ4cH+1ClXvlqN9knWjsphjnfRAOkUn3skolsOnTpZBwQRjdzBMAFb7/46CzRg59FWdEnDXMqmKDv74hij/STH0Le/LLlr85qWLAkd4+Rg5Rx1ryzV9PU7/7NnLc934X3wUCW7IEkG1SnvKsN+TmmLRA5IkMhN54xawFnnGgtiv1kslh36A949w4Rd3X3mj3FNEamJJNIUZjEBBiIa8QP6Fv9nLiguaSsF7SM0Q=}
